// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4oj3c7c27M9zk8FAYJ32lIpqgHFAUSPw',
    appId: '1:678303204493:web:1fa6257c031455975c4ec4',
    messagingSenderId: '678303204493',
    projectId: 'maintenancemobile-8f9b8',
    authDomain: 'maintenancemobile-8f9b8.firebaseapp.com',
    storageBucket: 'maintenancemobile-8f9b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0DyYDvnWcPP9BdZDaS7PfnWW1dXVyXjg',
    appId: '1:678303204493:android:baade97e81620b595c4ec4',
    messagingSenderId: '678303204493',
    projectId: 'maintenancemobile-8f9b8',
    storageBucket: 'maintenancemobile-8f9b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuHB6Yu6Ol2RUs6d5YxrBHv5-kpZAS5JM',
    appId: '1:678303204493:ios:2bcd36e1a61c59d05c4ec4',
    messagingSenderId: '678303204493',
    projectId: 'maintenancemobile-8f9b8',
    storageBucket: 'maintenancemobile-8f9b8.firebasestorage.app',
    iosBundleId: 'com.example.myflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuHB6Yu6Ol2RUs6d5YxrBHv5-kpZAS5JM',
    appId: '1:678303204493:ios:2bcd36e1a61c59d05c4ec4',
    messagingSenderId: '678303204493',
    projectId: 'maintenancemobile-8f9b8',
    storageBucket: 'maintenancemobile-8f9b8.firebasestorage.app',
    iosBundleId: 'com.example.myflutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4oj3c7c27M9zk8FAYJ32lIpqgHFAUSPw',
    appId: '1:678303204493:web:24947ed925d8591a5c4ec4',
    messagingSenderId: '678303204493',
    projectId: 'maintenancemobile-8f9b8',
    authDomain: 'maintenancemobile-8f9b8.firebaseapp.com',
    storageBucket: 'maintenancemobile-8f9b8.firebasestorage.app',
  );
}
